---
deployment:
  tasks:
    - export DEPLOYPATH=/home/alxihsql/narsolist.topg.eu.org/
    - /bin/cp * $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/css
    - /bin/mkdir -p $DEPLOYPATH/js
    - /bin/mkdir -p $DEPLOYPATH/static
    - /bin/cp -R css/* $DEPLOYPATH/css/
    - /bin/cp -R js/* $DEPLOYPATH/js/
    - /bin/cp -R static/* $DEPLOYPATH/static/
